api_key = "CHANGE_ME"
api_secret_key = "CHANGE_ME"
bearer_token = "CHANGE_ME"

# This can be any string, but must include either a URL or an email address. For example:
#contact_address = "Bob's research program about rockets; contact: <bob@bobsrockets.com>"
contact_address = "CHANGE_ME"
